server:
  port: 8033

spring:
  data:
    elasticsearch:
      cluster-name: my-application
      cluster-nodes: 1.117.214.155:9300

  datasource: # 数据源的相关配置
    type: com.zaxxer.hikari.HikariDataSource          # 数据源类型：HikariCP
    driver-class-name: com.mysql.jdbc.Driver          # mysql驱动
    url: jdbc:mysql://localhost:3306/foodie-shop-dev?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&
    username: root
    password: abc123456

